### ISSUE TITLE
access rights on a synology dsm

### ISSUE THREAD

**Issue by bierlos** [devdems/logitechmediaserver#5]
hello. i try to use your container on a synology nas. i use the synology shared music folder as /music read only volume in the container. on the console (root) i can see the whole music files. but the lms dont list mit the /music folder when i want to configure it. the lms runs as nobody/users right? how can i grant the nobody user access to the /music folder?

**Comment by snoopy86** [comment]
Not sure how Synology shares the drives to docker containers. I would try to give 755 permission on your host media folder.

**Comment by devdems** [comment]
Fixed. You can specify user and group id.
